import cz.cas.lib.arclib.service.FormatsRevisionNotificationService

FormatsRevisionNotificationService service = spring.getBean(FormatsRevisionNotificationService.class)
service.sendFormatsRevisionNotification(message)