import cz.cas.lib.arclib.service.preservationPlanning.FormatLibraryUpdater

FormatLibraryUpdater formatLibraryUpdater = spring.getBean(FormatLibraryUpdater.class)
formatLibraryUpdater.updateFormatsFromExternal(null)