package cz.cas.lib.arclib.bpm;

import cz.cas.lib.arclib.domain.Hash;
import cz.cas.lib.arclib.domain.HashType;
import cz.cas.lib.arclib.domain.ingestWorkflow.IngestWorkflow;
import cz.cas.lib.arclib.domain.ingestWorkflow.IngestWorkflowState;
import cz.cas.lib.arclib.index.IndexArclibXmlStore;
import cz.cas.lib.arclib.index.solr.arclibxml.IndexedArclibXmlDocumentState;
import cz.cas.lib.arclib.index.solr.arclibxml.SolrArclibXmlDocument;
import cz.cas.lib.arclib.service.arclibxml.ArclibXmlGenerator;
import cz.cas.lib.arclib.service.arclibxml.ArclibXmlXsltExtractor;
import cz.cas.lib.arclib.service.fixity.Sha512Counter;
import cz.cas.lib.arclib.store.IngestWorkflowStore;
import cz.cas.lib.core.store.Transactional;
import lombok.extern.slf4j.Slf4j;
import org.camunda.bpm.engine.delegate.DelegateExecution;
import org.camunda.bpm.engine.delegate.JavaDelegate;
import org.dom4j.Document;
import org.dom4j.DocumentException;
import org.springframework.stereotype.Component;

import javax.inject.Inject;
import javax.xml.transform.TransformerException;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Map;

import static cz.cas.lib.arclib.utils.ArclibUtils.prettyPrint;
import static cz.cas.lib.core.util.Utils.bytesToHexString;

@Slf4j
@Component
public class ArclibXmlGeneratorDelegate extends ArclibDelegate implements JavaDelegate {

    private ArclibXmlXsltExtractor arclibXmlXsltExtractor;
    private IndexArclibXmlStore indexArclibXmlStore;
    private ArclibXmlGenerator arclibXmlGenerator;
    private IngestWorkflowStore ingestWorkflowStore;
    private Sha512Counter sha512Counter;

    /**
     * Generates ArclibXml according to the BPM variables stored in the <code>execution</code> and changes processingState of
     * ingest workflow to PROCESSED.
     */
    @Transactional
    @Override
    public void execute(DelegateExecution execution) throws TransformerException, DocumentException, IOException {
        String ingestWorkflowExternalId = getIngestWorkflowExternalId(execution);
        log.info("Execution of ArclibXml generator delegate started for ingest workflow " + ingestWorkflowExternalId + ".");

        //extract metadata from original SIP using XSLT
        String extractedMetadata = arclibXmlXsltExtractor.extractMetadata(execution.getVariables());
        execution.setVariable(BpmConstants.MetadataExtraction.success, true);
        execution.setVariable(BpmConstants.MetadataExtraction.dateTime,
                Instant.now().truncatedTo(ChronoUnit.SECONDS).toString());

        //prepend the metadata generated by Arclib
        Document arclibXml = arclibXmlGenerator.generateMetadata(extractedMetadata, execution.getVariables());
        
        //store arclib xml to index
        String producerId = (String) execution.getVariable(BpmConstants.ProcessVariables.producerId);
        String assignee = (String) execution.getVariable(BpmConstants.ProcessVariables.assignee);
        indexArclibXmlStore.createIndex(prettyPrint(arclibXml), producerId, assignee, IndexedArclibXmlDocumentState.PROCESSED);
        String externalId = (String) execution.getVariable(BpmConstants.ProcessVariables.ingestWorkflowExternalId);
        log.info("ArclibXml of IngestWorkflow with external id " + externalId + " has been indexed.");

        Map<String, Object> arclibXmlIndexDocument = indexArclibXmlStore.findArclibXmlIndexDocument(ingestWorkflowExternalId);
        String indexedArclibXml = (String) ((ArrayList) arclibXmlIndexDocument.get(SolrArclibXmlDocument.DOCUMENT)).get(0);

        String arclibXmlHashValue = bytesToHexString(sha512Counter.computeDigest(new ByteArrayInputStream(indexedArclibXml.getBytes())));
        Hash arclibXmlHash = new Hash(arclibXmlHashValue, HashType.Sha512);
        IngestWorkflow ingestWorkflow = ingestWorkflowStore.findByExternalId(ingestWorkflowExternalId);
        ingestWorkflow.setArclibXmlHash(arclibXmlHash);
        log.info("Hash of ARClibXml of Ingest workflow with external ID " + ingestWorkflowExternalId + ": "
                + arclibXmlHash.getHashValue() + ", hash type: " + arclibXmlHash.getHashType().name());

        ingestWorkflow.setProcessingState(IngestWorkflowState.PROCESSED);
        ingestWorkflowStore.save(ingestWorkflow);
        log.info("State of ingest workflow with external id " + ingestWorkflowExternalId + " has changed to " +
                IngestWorkflowState.PROCESSED.toString() + ".");

        log.info("Execution of ArclibXml generator delegate finished for ingest workflow " + ingestWorkflowExternalId + ".");
    }
    @Inject
    public void setArclibXmlXsltExtractor(ArclibXmlXsltExtractor arclibXmlXsltExtractor) {
        this.arclibXmlXsltExtractor = arclibXmlXsltExtractor;
    }

    @Inject
    public void setIndexArclibXmlStore(IndexArclibXmlStore indexArclibXmlStore) {
        this.indexArclibXmlStore = indexArclibXmlStore;
    }

    @Inject
    public void setArclibXmlGenerator(ArclibXmlGenerator arclibXmlGenerator) {
        this.arclibXmlGenerator = arclibXmlGenerator;
    }

    @Inject
    public void setIngestWorkflowStore(IngestWorkflowStore ingestWorkflowStore) {
        this.ingestWorkflowStore = ingestWorkflowStore;
    }

    @Inject
    public void setSha512Counter(Sha512Counter sha512Counter) {
        this.sha512Counter = sha512Counter;
    }
}
