package cz.cas.lib.arclib.service.export;

public enum DcExportMetadataKey {
    DC_EXPORT_NDK_PUBLICATION_DATE,
    DC_EXPORT_NDK_NUMBER,
    DC_EXPORT_NDK_AUTHOR,
    DC_EXPORT_NDK_ISBN,
    DC_EXPORT_NDK_ISSN,
    DC_EXPORT_NDK_ISMN,
    DC_EXPORT_NDK_CNB,
    DC_EXPORT_NDK_URNNBN,
    DC_EXPORT_NDK_UUID,
    DC_EXPORT_NDK_BARCODE,
    DC_EXPORT_NDK_SIGNATURE,
    DC_EXPORT_NDK_SIGLA,
}
