package cz.cas.lib.arclib.security.authorization.permission;

import java.util.Set;

/**
 * @implNote Add new permissions into {@code ALL_PERMISSIONS} set!
 */
public interface Permissions {

    /**
     * Special/specific permissions
     */
    String SUPER_ADMIN_PRIVILEGE = "SUPER_ADMIN_PRIVILEGE";
    String ADMIN_PRIVILEGE = "ADMIN_PRIVILEGE";
    String DELETION_ACKNOWLEDGE_PRIVILEGE = "DELETION_ACKNOWLEDGE_PRIVILEGE";
    String EXPORT_FILES = "EXPORT_FILES";
    String UPDATE_XML = "UPDATE_XML";
    String LOGICAL_FILE_REMOVE = "LOGICAL_FILE_REMOVE";
    String LOGICAL_FILE_RENEW = "LOGICAL_FILE_RENEW";
    String REINDEX_ELIGIBILITY = "REINDEX_ELIGIBILITY";

    /**
     * Used in other module but copied into this module to include it in all permission set.
     *
     * @see cz.cas.lib.arclib.formatlibrary.Permissions#RISK_RECORDS_READ
     * @see cz.cas.lib.arclib.formatlibrary.Permissions#RISK_RECORDS_WRITE
     */
    String RISK_RECORDS_READ = Module.RISK_RECORDS + Operation.READ;
    String RISK_RECORDS_WRITE = Module.RISK_RECORDS + Operation.WRITE;

    /**
     * Classic permissions READ-WRITE
     */
    String INGEST_WORKFLOWS_READ = Module.INGEST_WORKFLOWS + Operation.READ;
    String AIP_RECORDS_READ = Module.AIP_RECORDS + Operation.READ;
    String USER_RECORDS_READ = Module.USER_RECORDS + Operation.READ;
    String USER_RECORDS_WRITE = Module.USER_RECORDS + Operation.WRITE;
    String BATCH_PROCESSING_READ = Module.BATCH_PROCESSING + Operation.READ;
    String BATCH_PROCESSING_WRITE = Module.BATCH_PROCESSING + Operation.WRITE;
    String DELETION_REQUESTS_READ = Module.DELETION_REQUESTS + Operation.READ;
    String DELETION_REQUESTS_WRITE = Module.DELETION_REQUESTS + Operation.WRITE;
    String EXPORT_ROUTINE_READ = Module.EXPORT_ROUTINE + Operation.READ;
    String EXPORT_ROUTINE_WRITE = Module.EXPORT_ROUTINE + Operation.WRITE;
    String FORMAT_RECORDS_READ = Module.FORMAT_RECORDS + Operation.READ;
    String FORMAT_RECORDS_WRITE = Module.FORMAT_RECORDS + Operation.WRITE;
    String NOTIFICATION_RECORDS_READ = Module.NOTIFICATION_RECORDS + Operation.READ;
    String NOTIFICATION_RECORDS_WRITE = Module.NOTIFICATION_RECORDS + Operation.WRITE;
    String INCIDENT_RECORDS_READ = Module.INCIDENT_RECORDS + Operation.READ;
    String INCIDENT_RECORDS_WRITE = Module.INCIDENT_RECORDS + Operation.WRITE;
    String ISSUE_DEFINITIONS_READ = Module.ISSUE_DEFINITIONS + Operation.READ;
    String ISSUE_DEFINITIONS_WRITE = Module.ISSUE_DEFINITIONS + Operation.WRITE;
    String INGEST_ROUTINE_RECORDS_READ = Module.INGEST_ROUTINE_RECORDS + Operation.READ;
    String INGEST_ROUTINE_RECORDS_WRITE = Module.INGEST_ROUTINE_RECORDS + Operation.WRITE;
    String PRODUCER_RECORDS_READ = Module.PRODUCER_RECORDS + Operation.READ;
    String PRODUCER_RECORDS_WRITE = Module.PRODUCER_RECORDS + Operation.WRITE;
    String PRODUCER_PROFILE_RECORDS_READ = Module.PRODUCER_PROFILE_RECORDS + Operation.READ;
    String PRODUCER_PROFILE_RECORDS_WRITE = Module.PRODUCER_PROFILE_RECORDS + Operation.WRITE;
    String REPORT_TEMPLATE_RECORDS_READ = Module.REPORT_TEMPLATE_RECORDS + Operation.READ;
    String REPORT_TEMPLATE_RECORDS_WRITE = Module.REPORT_TEMPLATE_RECORDS + Operation.WRITE;
    String SIP_PROFILE_RECORDS_READ = Module.SIP_PROFILE_RECORDS + Operation.READ;
    String SIP_PROFILE_RECORDS_WRITE = Module.SIP_PROFILE_RECORDS + Operation.WRITE;
    String TOOL_RECORDS_READ = Module.TOOL_RECORDS + Operation.READ;
    String TOOL_RECORDS_WRITE = Module.TOOL_RECORDS + Operation.WRITE;
    String VALIDATION_PROFILE_RECORDS_READ = Module.VALIDATION_PROFILE_RECORDS + Operation.READ;
    String VALIDATION_PROFILE_RECORDS_WRITE = Module.VALIDATION_PROFILE_RECORDS + Operation.WRITE;
    String WORKFLOW_DEFINITION_RECORDS_READ = Module.WORKFLOW_DEFINITION_RECORDS + Operation.READ;
    String WORKFLOW_DEFINITION_RECORDS_WRITE = Module.WORKFLOW_DEFINITION_RECORDS + Operation.WRITE;
    String AIP_QUERY_RECORDS_READ = Module.AIP_QUERY_RECORDS + Operation.READ;
    String AIP_QUERY_RECORDS_WRITE = Module.AIP_QUERY_RECORDS + Operation.WRITE;
    String STORAGE_ADMINISTRATION_READ = Module.STORAGE_ADMINISTRATION + Operation.READ;
    String STORAGE_ADMINISTRATION_WRITE = Module.STORAGE_ADMINISTRATION + Operation.WRITE;
    String USER_ROLE_RECORDS_READ = Module.USER_ROLE_RECORDS + Operation.READ;
    String USER_ROLE_RECORDS_WRITE = Module.USER_ROLE_RECORDS + Operation.WRITE;
    // ----- ADD NEW PERMISSIONS INTO 'ALL_PERMISSIONS' SET ! -----


    /**
     * Set of all permissions, used for validating permissions when creating roles with API
     */
    Set<String> ALL_PERMISSIONS = Set.of(
            SUPER_ADMIN_PRIVILEGE, ADMIN_PRIVILEGE, AIP_RECORDS_READ, EXPORT_FILES, UPDATE_XML,
            LOGICAL_FILE_REMOVE, LOGICAL_FILE_RENEW, INGEST_WORKFLOWS_READ,
            USER_RECORDS_READ, USER_RECORDS_WRITE, BATCH_PROCESSING_READ, BATCH_PROCESSING_WRITE,
            DELETION_REQUESTS_READ, DELETION_REQUESTS_WRITE, DELETION_ACKNOWLEDGE_PRIVILEGE,
            EXPORT_ROUTINE_READ, EXPORT_ROUTINE_WRITE, FORMAT_RECORDS_READ, FORMAT_RECORDS_WRITE,
            NOTIFICATION_RECORDS_READ, NOTIFICATION_RECORDS_WRITE, INCIDENT_RECORDS_READ, INCIDENT_RECORDS_WRITE,
            ISSUE_DEFINITIONS_READ, ISSUE_DEFINITIONS_WRITE, INGEST_ROUTINE_RECORDS_READ, INGEST_ROUTINE_RECORDS_WRITE,
            PRODUCER_RECORDS_READ, PRODUCER_RECORDS_WRITE, PRODUCER_PROFILE_RECORDS_READ, PRODUCER_PROFILE_RECORDS_WRITE,
            REPORT_TEMPLATE_RECORDS_READ, REPORT_TEMPLATE_RECORDS_WRITE,
            SIP_PROFILE_RECORDS_READ, SIP_PROFILE_RECORDS_WRITE, TOOL_RECORDS_READ, TOOL_RECORDS_WRITE,
            VALIDATION_PROFILE_RECORDS_READ, VALIDATION_PROFILE_RECORDS_WRITE,
            WORKFLOW_DEFINITION_RECORDS_READ, WORKFLOW_DEFINITION_RECORDS_WRITE,
            AIP_QUERY_RECORDS_READ, AIP_QUERY_RECORDS_WRITE, STORAGE_ADMINISTRATION_READ, STORAGE_ADMINISTRATION_WRITE,
            RISK_RECORDS_READ, RISK_RECORDS_WRITE, REINDEX_ELIGIBILITY,
            USER_ROLE_RECORDS_READ, USER_ROLE_RECORDS_WRITE
    );


    interface Module {
        String USER_RECORDS = "USER_RECORDS";
        String BATCH_PROCESSING = "BATCH_PROCESSING";
        String DELETION_REQUESTS = "DELETION_REQUESTS";
        String EXPORT_ROUTINE = "EXPORT_ROUTINE";
        String FORMAT_RECORDS = "FORMAT_RECORDS";
        String NOTIFICATION_RECORDS = "NOTIFICATION_RECORDS";
        String INCIDENT_RECORDS = "INCIDENT_RECORDS";
        String ISSUE_DEFINITIONS = "ISSUE_DEFINITIONS";
        String INGEST_ROUTINE_RECORDS = "INGEST_ROUTINE_RECORDS";
        String INGEST_WORKFLOWS = "INGEST_WORKFLOWS";
        String AIP_RECORDS = "AIP_RECORDS";
        String AIP_QUERY_RECORDS = "AIP_QUERY_RECORDS";
        String PRODUCER_RECORDS = "PRODUCER_RECORDS";
        String PRODUCER_PROFILE_RECORDS = "PRODUCER_PROFILE_RECORDS";
        String REPORT_TEMPLATE_RECORDS = "REPORT_TEMPLATE_RECORDS";
        String SIP_PROFILE_RECORDS = "SIP_PROFILE_RECORDS";
        String TOOL_RECORDS = "TOOL_RECORDS";
        String VALIDATION_PROFILE_RECORDS = "VALIDATION_PROFILE_RECORDS";
        String WORKFLOW_DEFINITION_RECORDS = "WORKFLOW_DEFINITION_RECORDS";
        String STORAGE_ADMINISTRATION = "STORAGE_ADMINISTRATION";
        String RISK_RECORDS = "RISK_RECORDS";
        String USER_ROLE_RECORDS = "USER_ROLE_RECORDS";
    }

    interface Operation {
        String READ = "_READ";
        String WRITE = "_WRITE";
    }
}
